Modelos de la base de datos
UNIZAR-30226-2021-07/backend pull request #24
Opened 2021-03-20 19:38 UTC by marioortizmanero

Closes #2

Para testearlo tendrás que hacer build, resetear la BBDD y volverla a crear.

2021-03-20 22:54 UTC, xzebra requested changes

2021-03-20 22:54 UTC, xzebra commented on README.md
>  $ # Inicializar la base de datos
Vendría bien poner el formato del fichero `.env`

2021-03-21 12:29 UTC, xzebra commented on gatovid/models.py
> +PROFILE_PICS_PATH = "assets/profile_pics.json"
No he conseguido que funcionen los `json.loads` con esta ruta, a pesar de haber montado bien lo del submódulo.
```
FileNotFoundError: [Errno 2] No such file or directory: './assets/profile_pics.json'
```
Creo que es porque la aplicación como tal no se ejecuta desde dentro de `./gatovid/`

2021-03-21 12:45 UTC, xzebra commented on gatovid/models.py
> +PROFILE_PICS_PATH = "assets/profile_pics.json"
Efectivamente, si cambiamos las rutas a `./gatovid/assets/profile_pics.json` funciona. Si encuentras una alternativa mejor lo dices.

2021-03-21 12:49 UTC, xzebra commented
Creo que hay que cambiar el action para que añada el submódulo.

2021-03-21 20:03 UTC, marioortizmanero commented on gatovid/models.py
> +PROFILE_PICS_PATH = "assets/profile_pics.json"
Lo mejor sería hacer la ruta relativa al archivo `models.py` con `dir_path = os.path.dirname(os.path.realpath(__file__))` porque si se invoca desde otro sitio o cualquier cosa se puede romper. Ahora lo arreglo.

2021-03-21 20:56 UTC, marioortizmanero commented
Ya están todos los cambios que faltaban. Échale un ojo y si se puede mergear ya adelante.

2021-03-21 21:03 UTC, xzebra commented on gatovid/models.py
> +CUR_DIR = os.path.dirname(os.path.realpath(__file__))
vale si, habia visto esto pero no sabia si era buena idea

2021-03-21 21:05 UTC, xzebra approved these changes

2021-03-21 21:06 UTC, merged